### ISSUE TITLE
yenma 2.0.0-rc1 does not terminate on FreeBSD stable/12

### ISSUE THREAD

**Issue by oikumene** [iij/yenma#12]
I am trying to update FreeBSD ports&packages' yenma to latest 2.0.0-rc1.
When terminating by the control command "GRACEFUL", the process terminates. (So, smfi_stop() is working.)
When terminating the process by kill -TERM, the process seem to close the control socket and milter socket, but the process itself remains running.

When sending SIGTERM, the log says:
<22>1 2021-02-14T17:05:34.656274+09:00 example.net yenma 3582 - - yenma: mi_stop=1
so, some shutdown procedure seems to be performed, but the process do not stop.

What can I do to determine where the problem is?

**Comment by nyan-** [comment]
I've sent a pull request to fix this issue.

**Comment by eraow** [comment]
As @nyan- said, this problem should to be solved by #14.
Please reply if any problem remained.
