### ISSUE TITLE
dkimsignature.c: DkimSignature_checkFutureTimestamp - do not make exact time compare

### ISSUE THREAD

**Issue by z3APA3A** [iij/yenma#2]
Because clocks are never consistent between different network system, few seconds in future for a timestamp is a common situation. Add additional condition in DkimSignature_checkFutureTimestamp e.g.
&& self->signing_timestamp - (long long) self_verification_time > 900 to discard DKIM signature as invalid.

**Comment by z3APA3A** [comment]
I've found OpenDKIM has ClockDrift configuration option, default is 300 seconds.

**Comment by takahiko** [comment]
Good Idea. I'll make that value configurable.

**Comment by takahiko** [comment]
Now configurable via Dkim.MaxClockSkew
