### ISSUE TITLE
$prefix is not extended in yenma.conf

### ISSUE THREAD

**Issue by z3APA3A** [iij/yenma#4]
1. 'make install' installs yenma.conf into /usr/local/etc (by default) without $prefix extended to path:

root@mailsrv-2:/usr/local/etc# grep prefix /usr/local/etc/yenma.conf
Service.PidFile: ${prefix}/var/yenma.pid
Dmarc.PublicSuffixList: ${prefix}/etc/effective_tld_names.dat
1. /var is not appropriate place for pid file, it's better to place one into $prefix/var/run/yenma or $prefix/var/run

**Comment by takahiko** [comment]
Thank you for reporting. I've fixed the configure script to expand these paths.

**Comment by z3APA3A** [comment]
Thanks.
