### ISSUE TITLE
Segfault (Ubuntu+postfix)

### ISSUE THREAD

**Issue by z3APA3A** [iij/yenma#6]
yenma segfaults periodically (Ubuntu + postfix):

root@mailsrv-2:/usr/local/libexec# grep yenma /var/log/kern.log
Feb 17 03:14:27 mailsrv-2 kernel: [583626.514566] yenma[6765]: segfault at 0 ip 00000000004066a2 sp 00007f359e5fdc60 error 4 in yenma[400000+1e000]
root@mailsrv-2:/usr/local/libexec# addr2line -e yenma 00000000004066a2
/root/yenma-master/yenma/yenmamfi.c:585

see proposed patch in pull request. With fix applied

root@mailsrv-2:/var/log# grep "milter host address is NULL" mail.log
Feb 17 03:44:35 mailsrv-2 yenma[8452]: error (at yenmamfi.c L581): milter host address is NULL
Feb 17 03:45:21 mailsrv-2 yenma[8452]: error (at yenmamfi.c L581): milter host address is NULL

**Comment by z3APA3A** [comment]
it seems to be the result of the TCP/25 half-scans:

Feb 17 03:44:35 mailsrv-2 postfix/smtpd[12315]: disconnect from unknown[unknown]
Feb 17 03:45:21 mailsrv-2 postfix/smtpd[11399]: connect from unknown[unknown]
Feb 17 03:45:21 mailsrv-2 postfix/smtpd[11399]: NOQUEUE: milter-reject: CONNECT from unknown[unknown]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
Feb 17 03:45:21 mailsrv-2 postfix/smtpd[11399]: lost connection after CONNECT from unknown[unknown]

**Comment by takahiko** [comment]
Thank you for the patch. I've merged it.

**Comment by z3APA3A** [comment]
Thanks
