### ISSUE TITLE
OpenSSL 1.1 support

### ISSUE THREAD

**Issue by hanazuki** [iij/yenma#9]
I would like to build YENMA on Debian 9, which ships with OpenSSL 1.1, but YENMA seems not to compile with OpenSSL 1.1 as it has several incompatible API changes since OpenSSL < 1.1.

Is there any plan YENMA to get support for OpenSSL 1.1? (I expect it as I see a recent commit that uses a feature from very new OpenSSL version...) If there is no active plan yet, I would be glad to provide a patch for it though.

Thanks.

**Comment by takahiko** [comment]
Can you show me your patch?

**Comment by hanazuki** [comment]
@takahiko Sure. Do you prefer to maintain OpenSSL-0.9.8 compatibility?

**Comment by takahiko** [comment]
Yes. But it depends on the complexity.
